[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "core"
version = "0.1.0"
description = "Shared types for use in multiple projects"
requires-python = ">=3.7"

[tool.setuptools.packages.find]
where = ["."]
